# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fcfae13a32954c2b14e26236e0518fb61fec11714d0f46b8d690cb40d5828489fe9c492f20cfd8f4e0258532c2993f8fdf7a6e3153c2934644ba770adb70a2ec

test:
  secret_key_base: dc16d732b4011bc99dfa1d038081897778ecb84a1207a8a3cfd86eb25b5a66450f9726dddfdf1d08ddf085f376762007111b65072ca078d4063e39ecdac5b9be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
